# ----------------------- #
#      Main Configs       #
# ----------------------- #
exclude: [node_modules, gulpfile.js]
url: http://yoursite.com
title: Veux Labs
email: your-email@domain.com
author: Veux Labs
description: > 
  VEUX WORKS WITH COMPANIES TO CREATE PRODUCTS AND APPS THAT HELP THEIR CUSTOMERS COMMUNICATE, COLLABORATE AND CONNECT.
copyright: 'Copyright © 2017 veux labs, Inc. All rights reserved.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: github
    url: https://github.com/VeuxLabs
  - title: linkedin
    url: https://www.linkedin.com/company/veux-labs
